python datafree_kd.py \
--method improved_cudfkd \
--dataset cifar10 \
--batch_size 1024 \
--teacher wrn40_2 \
--student wrn40_1 \
--lr 0.1 \
--epochs 250 \
--kd_steps 10 \
--kd_steps_interval 10 \
--g_steps_interval 1 \
--ep_steps 400 \
--g_steps 1 \
--lr_g 0.001 \
--begin_fraction 0.25 \
--end_fraction 0.75 \
--adv 1. \
--depth 2 \
--T 20 \
--lmda_ent -20 \
--oh 1 \
--act 0. \
--gpu 5 \
--seed 0 \
--bn 1 \
--save_dir run/cr7_pos_normal_wrn \
--log_tag cr7_pos_normal_wrn \
--data_root ~/cifar10/ \
--no_feature \
--adv_type kl \
--curr_option curr_log \
--lambda_0 1.0 \
--log_fidelity \
--mode memory \
--hard 1.0 \
--kld 0.5 \
--tau 0.07 \
--loss kl
