python datafree_kd.py \
--method deepinv \
--dataset cifar10 \
--batch_size 256 \
--teacher vgg11 \
--student resnet18 \
--lr 0.1 \
--epochs 250 \
--kd_steps 400 \
--ep_steps 400 \
--g_steps 1000 \
--lr_g 0.1 \
--adv 1 \
--bn 10 \
--oh 1 \
--T 20 \
--act 0 \
--balance 0 \
--gpu 3 \
--seed 0 \
--save_dir run/deepinv_3 \
--log_tag deepinv_3 \
--curr_option none \
--log_fidelity \
--data_root ~/cifar10/