python datafree_kd.py \
--method zskt \
--dataset cifar100 \
--batch_size 1024 \
--teacher vgg11 \
--student wrn40_1 \
--lr 0.1 \
--epochs 300 \
--kd_steps 5 \
--ep_steps 400 \
--g_steps 1 \
--lr_g 1e-3 \
--adv 1 \
--T 2 \
--bn 0 \
--oh 0 \
--act 0 \
--balance 0 \
--gpu 4 \
--seed 0 \
--log_fidelity \
--curr_option none \
--log_tag zskt_vary2_100 \
--loss kl \
--adv_type kl \
--data_root ~/cifar100/