# training setting
start_epoch: 0
n_epochs: 200
s_epochs: 300
s_iters: 5
network_s: resnet20_cifar10
network: resnet56_cifar10
warmup_epochs: 0
root: /data/lijingru/cifar10/
save_name: joint3
total_iters: 150
print_freq: 50
save_freq: 50
noise_scale: 1.0
tb_logger: 'none'

lr_s: 0.1
weight_decay: 0.

lr_g: 0.0005
beta_g1: 0.9
beta_g2: 0.999

batch_size: 256
num_workers: 8
ten_crop: False
nGPU: 1
n_cls: 10

alpha: 1.
temperature: 5.

img_size: 32
latent_dim: 256
no_DM: True
itermediate_dim: 256
channels: 3

random_embedding: True
set_tb_logger: True
# s_iter: 50000