# training setting
start_epoch: 0
n_epochs: 400
network_s: resnet20_cifar10
network: resnet56_cifar10
warmup_epochs: 4
root: /data/lijingru/cifar10/
save_name: test1

lr_s: 0.0001
weight_decay: 1e-4

lr_g: 0.001
beta_g1: 0.5
beta_g2: 0.999

batch_size: 256

img_size: 32
latent_dim: 128
no_DM: True
itermediate_dim: 256
channels: 3