python datafree_kd.py \
--method dfq \
--dataset cifar100 \
--batch_size 768 \
--teacher resnet34 \
--student resnet18 \
--lr 0.1 \
--epochs 400 \
--kd_steps 10 \
--ep_steps 400 \
--g_steps 1 \
--lr_g 1e-3 \
--adv 1 \
--T 5 \
--bn 1 \
--oh 1 \
--act 0 \
--balance 20 \
--gpu 0 \
--seed 0 \
--data_root /data/lijingru/cifar100 \
--log_tag dfq_retest_line4 \
--log_fidelity \
--curr_option none 