python datafree_kd.py \
--method dfq \
--dataset cifar10 \
--batch_size 1024 \
--teacher vgg11 \
--student wrn40_1 \
--lr 0.1 \
--epochs 250 \
--kd_steps 10 \
--ep_steps 400 \
--g_steps 1 \
--lr_g 1e-3 \
--adv 1 \
--T 5 \
--bn 1 \
--oh 1 \
--act 0 \
--balance 20 \
--gpu 5 \
--seed 0 \
--data_root ~/cifar10 \
--log_tag dfq_retest_vary2 \
--log_fidelity \
--curr_option none 