python datafree_kd.py \
--method cudfkd \
--dataset cifar100 \
--batch_size 768 \
--teacher resnet34 \
--student resnet18 \
--lr 0.1 \
--epochs 300 \
--kd_steps 5 \
--kd_steps_interval 10 \
--g_steps_interval 1 \
--ep_steps 400 \
--g_steps 1 \
--begin_fraction 0.2 \
--end_fraction 0.8 \
--grad_adv 0.35 \
--lr_g 0.001 \
--adv 0. \
--depth 2 \
--T 5 \
--lmda_ent -20 \
--oh 1 \
--act 0. \
--gpu 2 \
--seed 0 \
--bn 1 \
--save_dir run/cudfkd_test \
--log_tag cudfkd_L2_line33_g \
--data_root ../cifar100/ \
--no_feature \
--adv_type kl \
--curr_option curr_log \
--lambda_0 1 \
--log_fidelity \
--loss l1
# --resume /data/lijingru/DataFree/checkpoints/datafree-cudfkd/cifar10-resnet34-resnet18--cudfkd_dcgan_L2_adv_testrelu2.pth
