python datafree_kd.py \
--method cudfkd \
--dataset cifar100 \
--batch_size 1024 \
--teacher wrn40_2 \
--student wrn16_2 \
--lr 0.1 \
--epochs 300 \
--kd_steps 5 \
--kd_steps_interval 10 \
--g_steps_interval 1 \
--ep_steps 400 \
--g_steps 1 \
--lr_g 0.001 \
--adv 0. \
--depth 2 \
--T 2 \
--lmda_ent -20 \
--oh 1 \
--act 0. \
--gpu 1 \
--seed 0 \
--bn 1 \
--save_dir run/cudfkd_test \
--log_tag cudfkd_L2_line34_retest \
--begin_fraction 0.2 \
--end_fraction 0.75 \
--grad_adv 0.15 \
--data_root ~/cifar100/ \
--no_feature \
--adv_type kl \
--curr_option curr_log \
--lambda_0 1 \
--log_fidelity \
--loss kl