python datafree_kd.py \
--method cudfkd \
--dataset cifar10 \
--batch_size 768 \
--teacher resnet34 \
--student resnet18 \
--lr 0.1 \
--epochs 250 \
--kd_steps 200 \
--kd_steps_interval 400 \
--g_steps_interval 400 \
--ep_steps 400 \
--g_steps 400 \
--lr_g 0.001 \
--begin_fraction 0.25 \
--end_fraction 0.75 \
--grad_adv 0.0 \
--adv 0.0 \
--depth 2 \
--T 20 \
--lmda_ent -20 \
--oh 1 \
--act 0. \
--gpu 1 \
--seed 0 \
--bn 1 \
--save_dir run/cudfkd_mem_test \
--log_tag cudfkd_mem_test \
--data_root ../cifar10/ \
--no_feature \
--adv_type kl \
--curr_option curr_log \
--lambda_0 2.0 \
--log_fidelity \
--memory \
--loss kl
