python datafree_kd.py \
--method cudfkd \
--dataset svhn \
--batch_size 1024 \
--teacher wrn40_2 \
--student wrn40_1 \
--lr 0.1 \
--epochs 250 \
--kd_steps 10 \
--kd_steps_interval 10 \
--g_steps_interval 1 \
--ep_steps 400 \
--g_steps 1 \
--lr_g 0.001 \
--begin_fraction 0.25 \
--end_fraction 0.75 \
--grad_adv 0.03 \
--adv 0. \
--depth 2 \
--T 20 \
--lmda_ent -20 \
--oh 1 \
--act 0. \
--gpu 5 \
--seed 0 \
--bn 1 \
--save_dir run/cudfkd_retest \
--log_tag cudfkd_retest_log21 \
--data_root ~/svhn/ \
--no_feature \
--adv_type kl \
--curr_option curr_log \
--lambda_0 0.8 \
--log_fidelity \
--loss kl
