python datafree_kd.py \
--method cudfkd \
--dataset cifar10 \
--batch_size 1024 \
--teacher vgg11 \
--student wrn40_1 \
--lr 0.1 \
--epochs 250 \
--kd_steps 10 \
--ep_steps 400 \
--g_steps 1 \
--lr_g 0.001 \
--begin_fraction 0.25 \
--end_fraction 0.75 \
--grad_adv 0.2 \
--adv 0.1 \
--depth 2 \
--T 20 \
--lmda_ent -20 \
--oh 1 \
--act 0. \
--gpu 5 \
--seed 0 \
--bn 1 \
--save_dir run/cudfkd_retest_vary3 \
--log_tag cudfkd_retest_vary3 \
--data_root ~/cifar10/ \
--no_feature \
--adv_type kl \
--nt2_mode none \
--curr_option curr_log \
--lambda_0 2.0 \
--log_fidelity \
--loss kl
